export const DESTINATIONS = [
  {
    id: 1,
    name: 'Madurai',
    tagline: 'City of Temples',
    description: 'Home to the majestic Meenakshi Amman Temple, Madurai is one of India\'s oldest cities pulsating with culture and spirituality.',
    image: '/madurai.png',
    category: 'Heritage',
    rating: 4.9,
    tours: 12,
  },
  {
    id: 2,
    name: 'Rameswaram',
    tagline: 'Sacred Island City',
    description: 'A sacred pilgrimage site surrounded by the sea, known for the Ramanathaswamy Temple and the iconic Pamban Bridge.',
    image: '/rameswaram.png',
    category: 'Spiritual',
    rating: 4.8,
    tours: 8,
  },
  {
    id: 3,
    name: 'Kanyakumari',
    tagline: "Land's End",
    description: 'Where three oceans meet — experience breathtaking sunrises and sunsets at the southernmost tip of mainland India.',
    image: '/kanyakumari.png',
    category: 'Coastal',
    rating: 4.7,
    tours: 10,
  },
  {
    id: 4,
    name: 'Ooty',
    tagline: 'Queen of Hills',
    description: 'Nestled in the Nilgiri Mountains, Ooty offers lush tea gardens, serene lakes, and the charming Nilgiri Mountain Railway.',
    image: '/ooty.png',
    category: 'Hill Station',
    rating: 4.8,
    tours: 14,
  },
  {
    id: 5,
    name: 'Kodaikanal',
    tagline: 'Princess of Hill Stations',
    description: 'Known as the "Gift of the Forest," Kodaikanal charms visitors with its star-shaped lake, cascading waterfalls, and misty valleys.',
    image: '/kodaikanal.png',
    category: 'Hill Station',
    rating: 4.7,
    tours: 9,
  },
  {
    id: 6,
    name: 'Thanjavur',
    tagline: 'Temple City of South',
    description: 'The cultural capital of Tamil Nadu, renowned for the UNESCO-listed Brihadeeswarar Temple and classical Bharatanatyam dance.',
    image: '/tanjore.png',
    category: 'Heritage',
    rating: 4.6,
    tours: 7,
  },
  {
    id: 7,
    name: 'Velankanni',
    tagline: 'Lourdes of the East',
    description: 'A sacred coastal town home to the Basilica of Our Lady of Good Health — one of the most visited pilgrimage centers in Asia.',
    image: '/velankanni.png',
    category: 'Spiritual',
    rating: 4.6,
    tours: 6,
  },
  {
    id: 8,
    name: 'Courtallam',
    tagline: 'Spa of South India',
    description: 'Famous for its therapeutic waterfalls and lush green surroundings, Courtallam is nature\'s own spa retreat.',
    image: '/Courtallam.png',
    category: 'Nature',
    rating: 4.5,
    tours: 5,
  },
  // Kerala Destinations
  {
    id: 9,
    name: 'Munnar',
    tagline: 'Valley of Mist and Tea',
    description: 'Munnar is a breathtaking hill station in Kerala draped in rolling tea estates, misty mountains, and a cool climate year-round.',
    image: '/Munnar.png',
    category: 'Hill Station',
    rating: 4.9,
    tours: 11,
  },
  {
    id: 10,
    name: 'Alleppey',
    tagline: 'Venice of the East',
    description: 'Alleppey, or Alappuzha, is famous for its enchanting backwaters, houseboat stays, and lush paddy fields of Kerala.',
    image: '/Alleppey.avif',
    category: 'Coastal',
    rating: 4.8,
    tours: 9,
  },
  {
    id: 11,
    name: 'Varkala',
    tagline: 'Cliff-Side Beach Paradise',
    description: 'Varkala is a charming coastal town in Kerala known for its dramatic red laterite cliffs overlooking the Arabian Sea.',
    image: '/Varkala.png',
    category: 'Coastal',
    rating: 4.6,
    tours: 7,
  },
  {
    id: 12,
    name: 'Thekkady',
    tagline: 'Heart of Kerala Wildness',
    description: 'Home to the Periyar Wildlife Sanctuary, Thekkady offers thrilling elephant sightings, spice plantations and boat safaris.',
    image: '/Thekkady.png',
    category: 'Nature',
    rating: 4.7,
    tours: 8,
  },
  {
    id: 13,
    name: 'Kovalam',
    tagline: 'Crescent of Kerala Coast',
    description: "Kovalam is Kerala's most famous beach destination — three crescent beaches with crystal-clear waters and Ayurveda resorts.",
    image: '/Kovalam.png',
    category: 'Coastal',
    rating: 4.6,
    tours: 8,
  },
  {
    id: 14,
    name: 'Wayanad',
    tagline: 'Green Paradise of Kerala',
    description: 'Wayanad is a lush highland district in Kerala with ancient tribal heritage, mysterious caves, and cascading waterfalls.',
    image: '/Wayanad.png',
    category: 'Nature',
    rating: 4.7,
    tours: 8,
  },
  {
    id: 15,
    name: 'Kumarakom',
    tagline: 'Backwater Bird Paradise',
    description: 'Kumarakom is a cluster of tiny islands on Vembanad Lake, famed for its bird sanctuary, luxury resorts and tranquil backwaters.',
    image: '/Kumarakom.png',
    category: 'Nature',
    rating: 4.7,
    tours: 6,
  },
  {
    id: 16,
    name: 'Bekal',
    tagline: 'Fort by the Sea',
    description: 'Bekal is home to the largest fort in Kerala, set dramatically against the Arabian Sea — a serene and lesser-explored gem.',
    image: '/Bekal.png',
    category: 'Heritage',
    rating: 4.5,
    tours: 5,
  },
  {
    id: 17,
    name: 'Kochi',
    tagline: 'Queen of the Arabian Sea',
    description: 'Kochi is a cosmopolitan port city blending colonial architecture, Chinese fishing nets, vibrant art and Kerala spice heritage.',
    image: 'https://images.unsplash.com/photo-1598516493404-9a9aba698e4f?w=600&q=80',
    category: 'Heritage',
    rating: 4.7,
    tours: 10,
  },
  {
    id: 18,
    name: 'Thiruvananthapuram',
    tagline: "Capital of God's Own Country",
    description: "Kerala's capital combines ancient temples, colonial museums, and pristine beaches — all set against verdant rolling hills.",
    image: '/Thiruvananthapuram.png',
    category: 'Heritage',
    rating: 4.6,
    tours: 8,
  },
]

export const PACKAGES = [
  // ── TAMIL NADU PACKAGES ───────────────────────────────────────────────
  {
    id: 'pkg-1',
    name: 'Madurai Temple Tour',
    subtitle: 'Spiritual Heritage Experience',
    duration: '2 Days / 1 Night',
    price: 4999,
    originalPrice: 6500,
    image: '/madurai.png',
    destination: 'Madurai',
    category: 'Heritage',
    highlights: ['Meenakshi Amman Temple', 'Thirumalai Nayak Palace', 'Gandhi Museum', 'Night city tour'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Guide'],
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 245,
  },
  {
    id: 'pkg-2',
    name: 'Rameswaram Spiritual Tour',
    subtitle: 'Sacred Pilgrimage Journey',
    duration: '3 Days / 2 Nights',
    price: 7499,
    originalPrice: 9500,
    image: '/rameswaram.png',
    destination: 'Rameswaram',
    category: 'Spiritual',
    highlights: ['Ramanathaswamy Temple', 'Dhanushkodi', 'Pamban Bridge', "Adam's Bridge"],
    includes: ['AC Transport', 'Hotel Stay', 'All Meals', 'Guide'],
    badge: 'Popular',
    rating: 4.8,
    reviews: 189,
  },
  {
    id: 'pkg-3',
    name: 'Kanyakumari Sunset Tour',
    subtitle: 'Where Oceans Meet',
    duration: '2 Days / 1 Night',
    price: 5499,
    originalPrice: 7000,
    image: '/kanyakumari.png',
    destination: 'Kanyakumari',
    category: 'Coastal',
    highlights: ['Sunrise Point', 'Vivekananda Rock Memorial', 'Thiruvalluvar Statue', 'Suchindram Temple'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Boat Tickets'],
    badge: null,
    rating: 4.7,
    reviews: 156,
  },
  {
    id: 'pkg-4',
    name: 'Ooty Hill Station Package',
    subtitle: 'Queen of Hills Getaway',
    duration: '3 Days / 2 Nights',
    price: 7999,
    originalPrice: 10500,
    image: '/ooty.png',
    destination: 'Ooty',
    category: 'Hill Station',
    highlights: ['Ooty Lake Boating', 'Tea Garden Walk', 'Rose Garden', 'Doddabetta Peak', 'Nilgiri Train Ride'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Train Tickets', 'Guide'],
    badge: 'Popular',
    rating: 4.8,
    reviews: 218,
  },
  {
    id: 'pkg-5',
    name: 'Kodaikanal Escape',
    subtitle: 'Princess of Hill Stations',
    duration: '3 Days / 2 Nights',
    price: 7499,
    originalPrice: 9800,
    image: '/kodaikanal.png',
    destination: 'Kodaikanal',
    category: 'Hill Station',
    highlights: ['Kodaikanal Lake', "Coaker's Walk", 'Silver Cascade Falls', 'Pillar Rocks', 'Bryant Park'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Sightseeing', 'Guide'],
    badge: 'New',
    rating: 4.7,
    reviews: 174,
  },
  {
    id: 'pkg-5b',
    name: 'Thanjavur Heritage Circuit',
    subtitle: 'UNESCO World Heritage',
    duration: '2 Days / 1 Night',
    price: 4499,
    originalPrice: 5800,
    image: '/tanjore.png',
    destination: 'Thanjavur',
    category: 'Heritage',
    highlights: ['Brihadeeswarar Temple', 'Thanjavur Palace', 'Saraswathi Mahal Library', 'Art Gallery'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Guide'],
    badge: null,
    rating: 4.6,
    reviews: 98,
  },
  {
    id: 'pkg-6',
    name: 'Velankanni Pilgrimage Tour',
    subtitle: 'Lourdes of the East',
    duration: '2 Days / 1 Night',
    price: 3999,
    originalPrice: 5200,
    image: '/velankanni.png',
    destination: 'Velankanni',
    category: 'Spiritual',
    highlights: ['Basilica of Our Lady of Good Health', 'Velankanni Beach', 'Maritime Museum', 'Evening Mass', 'Local Market'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Guide'],
    badge: 'Devotion Special',
    rating: 4.7,
    reviews: 142,
  },
  {
    id: 'pkg-7',
    name: 'Courtallam Waterfall Retreat',
    subtitle: "Nature's Own Spa",
    duration: '2 Days / 1 Night',
    price: 3499,
    originalPrice: 4800,
    image: '/Courtallam.png',
    destination: 'Courtallam',
    category: 'Nature',
    highlights: ['Main Falls Bath', 'Five Falls', 'Papanasam Falls', 'Jungle Trek', 'Shenbagatham Temple'],
    includes: ['AC Transport', 'Hotel Stay', 'Breakfast', 'Guide'],
    badge: 'Nature Lover',
    rating: 4.5,
    reviews: 88,
  },
  {
    id: 'pkg-8',
    name: 'South Tamil Nadu Grand Tour',
    subtitle: 'Ultimate Tamil Nadu Experience',
    duration: '7 Days / 6 Nights',
    price: 24999,
    originalPrice: 32000,
    image: '/south.png',
    destination: 'Multiple Cities',
    category: 'Combo',
    highlights: ['Madurai', 'Rameswaram', 'Kanyakumari', 'Ooty', 'Kodaikanal', 'Thanjavur'],
    includes: ['AC Transport', 'Premium Hotels', 'All Meals', 'Expert Guide', 'All Tickets'],
    badge: 'Hot Deal',
    rating: 4.9,
    reviews: 421,
  },

  // ── KERALA PACKAGES ───────────────────────────────────────────────────
  {
    id: 'pkg-k1',
    name: 'Munnar Tea Hills Tour',
    subtitle: 'Misty Valleys and Tea Gardens',
    duration: '3 Days / 2 Nights',
    price: 8999,
    originalPrice: 12000,
    image: '/Munnar.png',
    destination: 'Munnar',
    category: 'Hill Station',
    highlights: ['Eravikulam National Park', 'Tea Museum', 'Mattupetty Dam', 'Top Station', 'Attukad Waterfalls'],
    includes: ['AC Transport', 'Resort Stay', 'All Meals', 'Guide', 'Park Entry'],
    badge: 'Kerala Favourite',
    rating: 4.9,
    reviews: 312,
  },
  {
    id: 'pkg-k2',
    name: 'Alleppey Houseboat Cruise',
    subtitle: 'Backwaters of Kerala',
    duration: '2 Days / 1 Night',
    price: 9499,
    originalPrice: 13000,
    image: '/Alleppey.avif',
    destination: 'Alleppey',
    category: 'Coastal',
    highlights: ['Overnight Houseboat Stay', 'Backwater Cruise', 'Village Boat Ride', 'Sunset on Vembanad Lake', 'Traditional Kerala Meals'],
    includes: ['AC Houseboat', 'All Meals on Board', 'Cruise', 'Welcome Drink'],
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 428,
  },
  {
    id: 'pkg-k3',
    name: 'Varkala Cliff Beach Escape',
    subtitle: 'Beach and Cliffs of Kerala',
    duration: '3 Days / 2 Nights',
    price: 7499,
    originalPrice: 9800,
    image: '/Varkala.png',
    destination: 'Varkala',
    category: 'Coastal',
    highlights: ['Papanasam Beach', 'Cliff Side Walk', 'Janardanaswamy Temple', 'Ayurveda Massage', 'Sunset Yoga'],
    includes: ['AC Transport', 'Beach Resort', 'Breakfast', 'Yoga Session'],
    badge: 'Trending',
    rating: 4.6,
    reviews: 187,
  },
  {
    id: 'pkg-k4',
    name: 'Thekkady Wildlife Safari',
    subtitle: 'Periyar Forest Adventure',
    duration: '3 Days / 2 Nights',
    price: 9999,
    originalPrice: 13500,
    image: '/Thekkady.png',
    destination: 'Thekkady',
    category: 'Nature',
    highlights: ['Periyar Lake Boat Safari', 'Elephant Encounters', 'Spice Plantation Tour', 'Bamboo Rafting', 'Jungle Night Walk'],
    includes: ['AC Transport', 'Forest Resort', 'All Meals', 'Boat Safari', 'Guide'],
    badge: 'Adventure Pick',
    rating: 4.8,
    reviews: 254,
  },
  {
    id: 'pkg-k5',
    name: 'Kovalam Beach and Ayurveda',
    subtitle: 'Sea, Sand and Healing',
    duration: '4 Days / 3 Nights',
    price: 12999,
    originalPrice: 17000,
    image: '/Kovalam.png',
    destination: 'Kovalam',
    category: 'Coastal',
    highlights: ['Lighthouse Beach', 'Hawa Beach', 'Ayurveda Full Body Treatment', 'Vizhinjam Mosque', 'Sunset Cruise'],
    includes: ['AC Transport', 'Beach Resort', 'Breakfast', 'Ayurveda Session', 'Cruise'],
    badge: 'Wellness Special',
    rating: 4.7,
    reviews: 199,
  },
  {
    id: 'pkg-k6',
    name: 'Wayanad Jungle Retreat',
    subtitle: 'Green Highlands of Kerala',
    duration: '3 Days / 2 Nights',
    price: 8499,
    originalPrice: 11500,
    image: '/Wayanad.png',
    destination: 'Wayanad',
    category: 'Nature',
    highlights: ['Edakkal Caves', 'Chembra Peak Trek', 'Banasura Sagar Dam', 'Pookode Lake', 'Tribal Village Visit'],
    includes: ['AC Transport', 'Jungle Cottage', 'All Meals', 'Trekking Guide'],
    badge: "Explorer's Choice",
    rating: 4.8,
    reviews: 221,
  },
  {
    id: 'pkg-k7',
    name: 'Kumarakom Backwater Bliss',
    subtitle: 'Islands on Vembanad Lake',
    duration: '3 Days / 2 Nights',
    price: 11999,
    originalPrice: 15500,
    image: '/Kumarakom.png',
    destination: 'Kumarakom',
    category: 'Nature',
    highlights: ['Kumarakom Bird Sanctuary', 'Canoe Ride', 'Houseboat Day Cruise', 'Village Walk', 'Fish Spa'],
    includes: ['AC Resort', 'All Meals', 'Canoe Ride', 'Bird Sanctuary Entry', 'Guide'],
    badge: 'Luxury Escape',
    rating: 4.8,
    reviews: 163,
  },
  {
    id: 'pkg-k8',
    name: 'Bekal Fort and Coast Tour',
    subtitle: 'Northern Kerala Heritage',
    duration: '3 Days / 2 Nights',
    price: 7999,
    originalPrice: 10500,
    image: '/Bekal.png',
    destination: 'Bekal',
    category: 'Heritage',
    highlights: ['Bekal Fort', 'Bekal Beach', 'Nityananda Ashram', 'Kappil Backwaters', 'Pallikere Beach'],
    includes: ['AC Transport', 'Beach Resort', 'Breakfast', 'Fort Entry', 'Guide'],
    badge: 'Hidden Gem',
    rating: 4.6,
    reviews: 122,
  },
  {
    id: 'pkg-k9',
    name: 'Kochi Heritage and Culture',
    subtitle: 'Queen of the Arabian Sea',
    duration: '3 Days / 2 Nights',
    price: 8999,
    originalPrice: 12000,
    image: 'https://images.unsplash.com/photo-1598516493404-9a9aba698e4f?w=700&q=80',
    destination: 'Kochi',
    category: 'Heritage',
    highlights: ['Fort Kochi Walk', 'Chinese Fishing Nets', 'Mattancherry Palace', 'Jewish Synagogue', 'Kathakali Performance'],
    includes: ['AC Transport', 'Heritage Hotel', 'Breakfast', 'Cultural Show', 'Guide'],
    badge: 'Cultural Pick',
    rating: 4.8,
    reviews: 286,
  },
  {
    id: 'pkg-k10',
    name: 'Thiruvananthapuram City Tour',
    subtitle: "Capital of God's Own Country",
    duration: '3 Days / 2 Nights',
    price: 7999,
    originalPrice: 10500,
    image: '/Thiruvananthapuram.png',
    destination: 'Thiruvananthapuram',
    category: 'Heritage',
    highlights: ['Padmanabhaswamy Temple', 'Napier Museum', 'Kovalam Beach Day Trip', 'Shanghumugham Beach', 'Zoo Visit'],
    includes: ['AC Transport', 'City Hotel', 'Breakfast', 'Museum Entry', 'Guide'],
    badge: 'Capital Special',
    rating: 4.6,
    reviews: 147,
  },
  {
    id: 'pkg-k11',
    name: 'Kerala Grand Tour',
    subtitle: "Best of God's Own Country",
    duration: '8 Days / 7 Nights',
    price: 29999,
    originalPrice: 40000,
    image: '/Kerala_Grand_Tour.png',
    destination: 'Kerala',
    category: 'Combo',
    highlights: ['Munnar Tea Hills', 'Thekkady Wildlife Safari', 'Alleppey Houseboat', 'Kovalam Beach', 'Kochi Heritage Walk', 'Wayanad Jungle'],
    includes: ['AC Transport', 'Premium Hotels', 'All Meals', 'Expert Guide', 'All Tickets', 'Houseboat Night'],
    badge: 'Best Value',
    rating: 4.9,
    reviews: 538,
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Priya Sharma',
    location: 'Mumbai',
    avatar: 'https://i.pravatar.cc/80?img=1',
    rating: 5,
    text: 'The Madurai Temple Tour was absolutely life-changing. Our guide was knowledgeable, the hotel was excellent, and every moment felt curated perfectly. Will book again!',
    tour: 'Madurai Temple Tour',
  },
  {
    id: 2,
    name: 'Rahul Verma',
    location: 'Delhi',
    avatar: 'https://i.pravatar.cc/80?img=12',
    rating: 5,
    text: 'Vaigai Tourism made our family trip to Ooty seamless. Kids loved every moment, especially the Nilgiri train ride. Highly recommended!',
    tour: 'Ooty Hill Station Package',
  },
  {
    id: 3,
    name: 'Meena Krishnan',
    location: 'Bangalore',
    avatar: 'https://i.pravatar.cc/80?img=5',
    rating: 5,
    text: 'Best service I have ever experienced with a travel company. The Rameswaram spiritual tour was deeply moving. Professional, punctual and very affordable.',
    tour: 'Rameswaram Spiritual Tour',
  },
  {
    id: 4,
    name: 'Suresh Nair',
    location: 'Kochi',
    avatar: 'https://i.pravatar.cc/80?img=33',
    rating: 4,
    text: 'Kanyakumari at sunrise is something else entirely. Vaigai Tourism handled everything perfectly — transport, accommodation, everything was top notch.',
    tour: 'Kanyakumari Sunset Tour',
  },
  {
    id: 5,
    name: 'Ananya Iyer',
    location: 'Chennai',
    avatar: 'https://i.pravatar.cc/80?img=9',
    rating: 5,
    text: 'The Grand South Tamil Nadu Tour covered everything I ever wanted to see. 7 days of pure bliss. Our guide Ravi was exceptional — funny, wise and so helpful.',
    tour: 'Grand South TN Tour',
  },
  {
    id: 6,
    name: 'Divya Menon',
    location: 'Trivandrum',
    avatar: 'https://i.pravatar.cc/80?img=20',
    rating: 5,
    text: 'The Alleppey Houseboat experience was a dream come true. Waking up on the backwaters with freshly made Kerala breakfast — absolutely magical!',
    tour: 'Alleppey Houseboat Cruise',
  },
  {
    id: 7,
    name: 'Arun Pillai',
    location: 'Pune',
    avatar: 'https://i.pravatar.cc/80?img=41',
    rating: 5,
    text: 'Munnar was everything I hoped for and more. The tea garden walks, cool climate, and cozy resort — all perfectly arranged. Highly recommend!',
    tour: 'Kerala Grand Tour',
  },
]

export const GALLERY_IMAGES = [
  { id: 1, src: '/madurai.png', alt: 'Meenakshi Temple', span: 'col-span-2 row-span-2' },
  { id: 2, src: '/rameswaram.png', alt: 'Rameswaram' },
  { id: 3, src: '/kanyakumari.png', alt: 'Kanyakumari' },
  { id: 4, src: '/ooty.png', alt: 'Ooty' },
  { id: 5, src: '/kodaikanal.png', alt: 'Kodaikanal' },
  { id: 6, src: '/tanjore.png', alt: 'Thanjavur' },
  { id: 7, src: '/Courtallam.png', alt: 'Courtallam', span: 'col-span-2' },
  { id: 8, src: '/Munnar.png', alt: 'Munnar' },
  { id: 9, src: '/Alleppey.avif', alt: 'Alleppey Backwaters' },
]
